/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Setups',
      [
        {
          body: 'Явный признак того, что твои родители тебя усыновили?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Как по-другому назвать одичное заключение в тюрьме, чтобы это звучало получше?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Это определенно не стоит говорить находясь рядом с Квантумом?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Как ленивый ковбой назвал свою лошадку?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Хороший способ завести друзей в парилке - снять полотенце и _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самое сильное заявление, которое можно объявить, покидая комнату?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'То, что ты не ожидал прочесть на записке из бутылки?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Вопрос, на который наука никогда не ответит?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Когда аисты не приносят детей, они _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Как назывался бы 13-ый месяц в году?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Придумайте новое название для патриотичных подгузников?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'В учебниках истории в разделе про 2007-ой обязательно напишут про?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Если Иваново - город невест, то Воронеж - город _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самое страшное, что ты можешь найти в пещере?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Если бы усы Якубовича могли говорить, чтобы они сказали?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Что расстраивает капитана Врунгеля?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Негласное название озера Титикака?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Три ингредиента коктейля под названием "Сочи"?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: '_____ улетел, но обещал вернуться?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Лайфхак! Если ты не можешь позволить себе винный погреб, просто используй _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Если повстречал горного льва, не кипишуй: выпрямься как можно выше и _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'После какого слова точно не надо ставить восклицательный знак?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Говорящее название вымышленного города в Австралии?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Первое, менее страшное название фильма Челюсти?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Сокровенная тайна об олимпийском Мишке, которую никто не знает?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Откуда берутся фигурки в Тетрисе?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Ты очень богат, если у тебя есть ложка специально для _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Можно ожидать трагическое будущее, если гадалка вытаскивает карту таро с _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самое странное, что можно обнаружить после выхода из состояния наркоза?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Три вещи, которые можно услышать в месте, где все ходят голышом?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Как можно описать и бутерброд и поцелуй?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Худшее, что можно сказать с набитым картошкой ртом?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Три вещи, которые стоит уточнить перед покупкой обручального кольца?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'А вот и останки самого неуклюжего динозавра в мире, который называется _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Худшая причина расстаться: "Проблема не в тебе, проблема в _____"',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Кто же знал, что полиция теперь штрафует за _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Что за страшный и загадочный монстр крадется по улицам Воронежа?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Капитан рыбацкого судна может теперь всю жизнь не работать, ведь он обнаружил в сети _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Что бы сделала кошка, если бы у нее были человеческие руки?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Название новой полицейской драмы о преступлениях в небе?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Вкус жидкостей для вейпа, созданный специально для людей старше 70 лет?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Чего никогда не услышишь, работая кассиром в Пятёрочке?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Знак того, что ты медленно, но верно превращаешься в белку?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'В бомбоубежище осталось мало места, но ПИНГВИН настаивает на том, чтобы притащить _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самое худшее, что отец может сказать своему сыну в день его свадьбы?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Настоящая причина, по которой ты пошёл сегодня играть с этими дураками?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Блюдо в китайском ресторане, которое все боятся заказывать?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Что-то, что можно случайно услышать в Кремле?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Будем честны: вам никогда не хватает сил, чтобы _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Эротический боевик, который никто не хочет смотреть: "Запретные дневники _____"',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Имя, от которого учитель постоянно давится от смеха во время переклички?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Худшая часть работы телохранителя Джастина Бибера?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Неосторожная фраза президента: у меня не было _____ с этой женщиной?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'То, что бабушка связала тебе шарф - прекрасно. Плохо то, что она теперь вяжет для тебя _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Страшнейшее преступление в Средиземье?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Как понять, что у тебя в квартире живет человек-невидимка?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Кто в доме хозяин?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Какую книгу никогда не берут в библиотеке?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Неподходящий момент для разрядившегося телефона?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Задание, которое ученик сатаны ненавидит больше всего?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Несуществующая работа, на которой умирают чаще всех?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Придумайте расшифровку этого акронима - Х.Р.Я.',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Будет весело поменяться местами с близнецом во время?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Чего бы тебе не хотелось услышать от стригущего тебя парикмахера?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Странный способ спасти амурских тигров?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Странное объявление на входе в рай: _____ каждый вечер по вторникам?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Худшее, что ты можешь услышать во время массажа?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Секрет твоей вкусной яичницы - просто _____',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Фильм, в котором позарез не хватает эротических сцен?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самая странная вещь, которую рекламировал Игорь Верник?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Название книги рецептов, написанной ковбоем?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'То, что никогда не должно быть начинкой шоколадных конфет?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Самое подходящее и осторожное название кабельного канала для взрослых?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Состав идеального ансамбля: Осёл, Козёл, Мартышка, ___ и косолапый Мишка?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Опасная штука, с которой к тебе летит дрон?',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body: 'Придумайте расшифровку этого акронима - В.И.Д.',
          gameId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],

      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
  },
};
